# top.xdc - Genesys 2 (Kintex-7 XC7K325T-2FFG900C)
#
# Top-level ports defined in top.sv:
#   clk_p, clk_n   - 200 MHz LVDS system clock (bank 33)
#   reset_rtl_0    - CPU reset pushbutton (active-low; see note)
#   uart_rxd       - FPGA UART receive  (from USB-UART bridge)
#   uart_txd       - FPGA UART transmit (to USB-UART bridge)
#   led_gpu_done   - LED0 mirror of GPU_done
#
# The 100 MHz internal clock is generated by the Clock Wizard inside the
# block design. The wizard's auto-generated XDC creates the timing
# constraints for clk_out1, so no manual create_clock is needed here.
# (Confirmed by the implementation timing report: the clock is named
# clk_out1_GPU_Design_clk_wiz_1_0 with period 10.000 ns.)

# ── 200 MHz differential system clock (LVDS, bank 33) ─────────────────────
set_property -dict { PACKAGE_PIN AD12  IOSTANDARD LVDS } [get_ports clk_p]
set_property -dict { PACKAGE_PIN AD11  IOSTANDARD LVDS } [get_ports clk_n]

# ── CPU reset (CPU_RESETN, active-low pushbutton) ─────────────────────────
# NOTE: This pin is active LOW. The Processor System Reset block in your
# BD must have Ext_Reset_High = 0 (active-low ext_reset_in). If the BD is
# currently configured active-high, either change that parameter or move
# this constraint to a regular pushbutton (e.g. BTNC at E18 LVCMOS12).
set_property -dict { PACKAGE_PIN R19  IOSTANDARD LVCMOS33 } [get_ports reset_rtl_0]

# ── UART (USB-UART bridge) ────────────────────────────────────────────────
# Digilent uses terminal-centric naming on the board: their uart_rxd_out
# is the FPGA's TX, and their uart_txd_in is the FPGA's RX.
set_property -dict { PACKAGE_PIN Y20  IOSTANDARD LVCMOS33 } [get_ports uart_rxd]  ;# FPGA RX  (board uart_txd_in)
set_property -dict { PACKAGE_PIN Y23  IOSTANDARD LVCMOS33 } [get_ports uart_txd]  ;# FPGA TX  (board uart_rxd_out)

# ── Status LED (LED0) ─────────────────────────────────────────────────────
set_property -dict { PACKAGE_PIN T28  IOSTANDARD LVCMOS33 } [get_ports led_gpu_done]

# ── False paths ───────────────────────────────────────────────────────────
# Async reset input - synchronized by the Processor System Reset block.
set_false_path -from [get_ports reset_rtl_0]
# LED output - visual indicator, no real timing requirement.
set_false_path -to   [get_ports led_gpu_done]

# ── Bitstream config (Genesys 2 boots from 1.8 V QSPI flash) ──────────────
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS         GND [current_design]